name: YzdWihteList
version: ${project.version}
main: YzdWihteList
api-version: 1.15
commands:
  add:
    description: add
  ti:
    description: kick
  remove:
    description: re
  look:
    description: look